### ISSUE TITLE
Images are not being saved/cached and are requested over and over again

### ISSUE THREAD

**Issue by DailySmoker** [mladenilic/threesixty#16]
Hi there, I am trying to use your plugin, but I notices a slight problem.
I am passing an array of 50 images. First I preload the images, then I call your plugin.

The problem is that every time I rotate, the plugin reloads the images even if they are loaded already.

If I fully rotate the object 5 times for example, in the "network tab" in Chrome, there are 250 requests.
This causes flickering because each time the images are being loaded again.

Is there a way to solve this?

Thanks

**Comment by mladenilic** [comment]
Hi there!
Can you please check if your browser cache is enabled (please check the image below)? Once the images are loaded, the browser should not make requests for same assets.

![chrome-cache](https://user-images.githubusercontent.com/7901221/69810963-59d0d100-11ed-11ea-9e07-5b4228d43b66.png)

**Comment by DailySmoker** [comment]
"Disable cache" is unchecked, link in your picture.
I tried an alternative plugin and this problem does not happen, I can't understand what causes it.

**Comment by mladenilic** [comment]
Can you share you code, I'd like to try and recreate so I can try and understand what's going on.

**Comment by DailySmoker** [comment]
Sure, here is the gist https://gist.github.com/DailySmoker/1be26aaa2860dfbb133601cfc43850af

**Comment by mladenilic** [comment]
Thanks for the example. When I run it, I can see that the images are initially loaded and then afterwards, they are loaded again from **memory cache**.

![Screen Shot 2019-11-28 at 4 40 28 PM](https://user-images.githubusercontent.com/7901221/69818780-d10e6100-11fd-11ea-8a35-3691b89a2d86.png)

This is what we expect to happen, so that's cool. However, I noticed that from time to time, images get reloaded from **disk cache** and there's some flickering going on while this is happening. 

![Screen Shot 2019-11-28 at 4 41 31 PM](https://user-images.githubusercontent.com/7901221/69818885-074be080-11fe-11ea-8226-b61a0848c1a2.png)

It's hard to know for sure why are images being kicked out of the memory cache, but my guess is that they are being garbage collected. The fact that they are being loaded from disk cache is ok, since at least browser is not making new network request, but still I think we can do better.

My approach was to add images to the DOM that way making sure they are not garbage collected and always kept in the memory cache. I adjusted your preloading code a bit to accomplish this:

```js
const images = [
  ...
];

Promise.all(images.map((src) => {
  return new Promise((resolve, reject) => {
    const image = new Image();

    image.onload = resolve;
    image.onerror = resolve;

    image.style.display = 'none';
    image.src = src;

    // Here we append image to the document body
    document.body.appendChild(image);
  })
})).then(() => {
  const threesixty = new ThreeSixty(document.getElementById('threesixty'), {
    image: images,
    width: 400,
    height: 400,
    speed: 200,
  });

  threesixty.play();
});
```

You can find the full example here: https://codepen.io/mladenilic/pen/rNNXZyR?editors=1010

I wasn't able to find and concrete resources on how memory/disk cache works in chrome, so this is basically an educated guess, but it does solve the problem. 

If you'd like to avoid adding images to the DOM, you could probably get away even by keeping global references to the image objects, that should prevent garbage collection as well. I haven't tested this tho.

Please try and let me know how it goes! :)

**Comment by DailySmoker** [comment]
Thank you for taking the time to help me.

The images were loaded from cache each time it's true, but the flickering was noticeable.

Using your updated code seems to have solved the problem, so again, thank you a lot :)
